### ISSUE TITLE
"liquibase.exception.ValidationFailedException" while starting application

### ISSUE THREAD

**Issue by Rajiv-mar121** [kdhrubo/crx#328]
liquibase.exception.ValidationFailedException: Validation Failed:
     1 change sets check sum
          db.changelog.tenant.xml::tenant-4::effectiv was: 7:079f329662a95ec8393f2bb8feb4e357 but is now: 7:7c164037ae369d0fd2dd92b455a0870e

	at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:266) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:210) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:192) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:188) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:181) ~[liquibase-core-3.5.3.jar:na]
	at com.effectiv.crm.multitenant.MariaDbTenantProvisioningHelper.provisionTenant(MariaDbTenantProvisioningHelper.java:65) ~[bin/:na]
	at com.effectiv.crm.multitenant.MultiTenantProvisioningEventHandler.handle(MultiTenantProvisioningEventHandler.java:31) [bin/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:253) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:174) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:137) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at com.effectiv.crm.business.UserBusinessDelegate.activate(UserBusinessDelegate.java:150) [bin/:na]

**Comment by kdhrubo** [comment]
@This is not a bug. We have fixed the ways of working with Liquibase.
